#!/bin/bash
set -e

BUILD_IMAGE_NAME="go-dnsmasq-build"
# GOOS=${GOOS:-"darwin linux windows"}
# GOARCH=${GOARCH:-"386 amd64 arm"}
GOOS=${GOOS:-"darwin linux"}
GOARCH=${GOARCH:-"amd64"}

# Build image for compilation if not detected
if [[ $(docker images -q ${BUILD_IMAGE_NAME} | wc -l) -ne 1 ]]; then
    docker build -t ${BUILD_IMAGE_NAME} -f Dockerfile.build .
fi

echo "building full version"

git checkout master
sleep 2

docker run --rm \
    -v `pwd`:/go/src/github.com/janeczku/go-dnsmasq \
    ${BUILD_IMAGE_NAME} \
    gox \
    -os "$GOOS" \
    -arch "$GOARCH" \
    -output="go-dnsmasq_{{.OS}}-{{.Arch}}" \
    -ldflags="-w -s" \
    -tags="netgo" \
    -rebuild
