#!/bin/bash
set -e

if [ -z "$1" ]; then
    echo "The version number must be passed to this script"
    exit 1
fi
VERSION=$1

echo "building binary $VERSION"

BUILD_IMAGE_NAME="go-dnsmasq-build"
GOOS=${GOOS:-"darwin linux"}
# GOARCH=${GOARCH:-"386 amd64 arm"}
GOARCH=${GOARCH:-"amd64"}

# Build image for compilation if not detected
if [[ $(docker images -q ${BUILD_IMAGE_NAME} | wc -l) -ne 1 ]]; then
    docker build -t ${BUILD_IMAGE_NAME} -f Dockerfile.build .
fi

echo "building minmal version"

git checkout minimal
sleep 2

docker run --rm \
    -v `pwd`:/go/src/github.com/janeczku/go-dnsmasq \
    ${BUILD_IMAGE_NAME} \
    gox \
    -os "$GOOS" \
    -arch "$GOARCH" \
    -output="go-dnsmasq-min_{{.OS}}-{{.Arch}}" \
    -ldflags "-w -s -X main.Version=$VERSION" \
    -tags="netgo" \
    -rebuild

git checkout master
